# Generated by Django 4.2.2 on 2023-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='country',
            name='img',
        ),
        migrations.RemoveField(
            model_name='country',
            name='verified_Country',
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='No Capital', max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='No Currency', max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.URLField(default='No Image URL', max_length=400),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(default='No Language', max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Unnamed Country', max_length=200),
        ),
    ]
