# Generated by Django 4.2.2 on 2023-07-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_country_bio_remove_country_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
    ]
