# Generated by Django 4.2.2 on 2023-07-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('length', models.IntegerField(default=0)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='main_app.country')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
