# Generated by Django 4.2.2 on 2023-07-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('budget_range', models.CharField(max_length=200)),
                ('image', models.URLField(default='No Image URL', max_length=400)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='main_app.country')),
            ],
        ),
    ]
