# Generated by Django 4.2.2 on 2023-07-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('countries', models.ManyToManyField(related_name='itineraries', to='main_app.country')),
                ('destinations', models.ManyToManyField(related_name='itineraries', to='main_app.destination')),
            ],
        ),
    ]
