# Generated by Django 4.2.2 on 2023-07-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_country_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('budget_range', models.CharField(max_length=200)),
                ('image', models.URLField(default='No Image URL', max_length=400)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.country')),
            ],
        ),
    ]
